// ─── Component System (Updated) ────────────────────────────────────────────────
// Now supports capacity-based multi-selection per pillar.
// 27 components total. Capacity: Ideation (2), Design (3), Development (3), Marketing (2)

export const PILLARS = ['Ideation', 'Design', 'Development', 'Marketing'];

export const PILLAR_CAPACITY = {
    Ideation: 2,
    Design: 3,
    Development: 3,
    Marketing: 2,
};

export const COMPONENTS = [
    // ── IDEATION ─────────────────────────────────────────────────────────────
    {
        id: 'clear_idea',
        name: 'Clear Idea',
        pillar: 'Ideation',
        icon: '👁️',
        cost: 300,
        capacityCost: 1,
        devTime: 0.2,
        quality: 1.0, innovation: 0, retention: 0.5, marketingPower: 0,
        risk: -0.1,
        tags: ['focused'],
        unlockCondition: { type: 'free' },
        description: 'A solid, simple plan. Good for quality and retention.',
    },
    {
        id: 'trend_surfing',
        name: 'Trend Surfing',
        pillar: 'Ideation',
        icon: '🌊',
        cost: 600,
        capacityCost: 1,
        devTime: 0.1,
        quality: 0.2, innovation: 0.5, retention: 0, marketingPower: 0.8,
        risk: 0.05,
        tags: ['trend'],
        unlockCondition: { type: 'free' },
        description: 'Ride the hype. High marketing power and innovation.',
    },
    {
        id: 'scratch_itch',
        name: 'Scratch My Own Itch',
        pillar: 'Ideation',
        icon: '🩹',
        cost: 400,
        capacityCost: 1,
        devTime: 0.3,
        quality: 0.5, innovation: 0.8, retention: 1.2, marketingPower: 0,
        risk: 0,
        tags: ['passion'],
        unlockCondition: { type: 'free' },
        description: 'Solve a personal problem. High retention and innovation.',
    },
    {
        id: 'copy_works',
        name: 'Copy What Works',
        pillar: 'Ideation',
        icon: '📋',
        cost: 500,
        capacityCost: 1,
        devTime: 0.1,
        quality: 0.4, innovation: -0.5, retention: 0.3, marketingPower: 0.2,
        risk: -0.2,
        tags: ['copy'],
        unlockCondition: { type: 'free' },
        description: 'Follow the leaders. Lowers risk significantly.',
    },
    {
        id: 'small_focused',
        name: 'Small But Focused',
        pillar: 'Ideation',
        icon: '🔍',
        cost: 200,
        capacityCost: 1,
        devTime: 0.1,
        quality: 0.6, innovation: 0.2, retention: 0.4, marketingPower: 0,
        risk: -0.15,
        tags: ['focused'],
        unlockCondition: { type: 'free' },
        description: 'Do one thing well. Fast and reliable.',
    },
    {
        id: 'audience_first',
        name: 'Audience First',
        pillar: 'Ideation',
        icon: '👥',
        cost: 1200,
        capacityCost: 1,
        devTime: 0.8,
        quality: 1.2, innovation: 0, retention: 2.0, marketingPower: 0.5,
        risk: -0.05,
        tags: ['strategy', 'data'],
        unlockCondition: { type: 'mastery', releases: 3 },
        description: 'Build what they want. Massive retention boost.',
    },
    {
        id: 'long_term_plan',
        name: 'Long-Term Plan',
        pillar: 'Ideation',
        icon: '📅',
        cost: 1500,
        capacityCost: 1,
        devTime: 1.2,
        quality: 1.5, innovation: 0, retention: 1.0, marketingPower: 0,
        risk: -0.1,
        tags: ['strategy'],
        unlockCondition: { type: 'mastery', releases: 5 },
        description: 'Think ahead. Great for long-term project viability.',
    },

    // ── DESIGN ───────────────────────────────────────────────────────────────
    {
        id: 'clean_look',
        name: 'Clean Look',
        pillar: 'Design',
        icon: '✨',
        cost: 400,
        capacityCost: 1,
        devTime: 0.3,
        quality: 0.8, innovation: 0, retention: 0.2, marketingPower: 0.5,
        risk: -0.05,
        tags: ['design'],
        unlockCondition: { type: 'free' },
        description: 'Looks professional. Boosts quality and hype.',
    },
    {
        id: 'simple_smooth',
        name: 'Simple & Smooth',
        pillar: 'Design',
        icon: '🧈',
        cost: 600,
        capacityCost: 1,
        devTime: 0.4,
        quality: 0.5, innovation: 0, retention: 1.0, marketingPower: 0,
        risk: -0.1,
        tags: ['ux'],
        unlockCondition: { type: 'free' },
        description: 'Fast and fluid interface. Keeps users coming back.',
    },
    {
        id: 'dark_mode',
        name: 'Dark Mode Ready',
        pillar: 'Design',
        icon: '🌙',
        cost: 300,
        capacityCost: 1,
        devTime: 0.2,
        quality: 0.3, innovation: 0.2, retention: 0.6, marketingPower: 0.4,
        risk: 0,
        tags: ['design'],
        unlockCondition: { type: 'free' },
        description: 'Everyone loves it. Small boost across the board.',
    },
    {
        id: 'brand_vibes',
        name: 'Brand Vibes',
        pillar: 'Design',
        icon: '🎨',
        cost: 800,
        capacityCost: 1,
        devTime: 0.6,
        quality: 0.5, innovation: 0.5, retention: 0, marketingPower: 1.5,
        risk: 0,
        tags: ['brand'],
        unlockCondition: { type: 'free' },
        description: 'Strong visual identity. Great for marketing.',
    },
    {
        id: 'feels_polished',
        name: 'Feels Polished',
        pillar: 'Design',
        icon: '💎',
        cost: 1000,
        capacityCost: 1,
        devTime: 0.8,
        quality: 1.5, innovation: 0, retention: 0.8, marketingPower: 0.2,
        risk: -0.1,
        tags: ['polish'],
        unlockCondition: { type: 'free' },
        description: 'Premium feel. High quality and decent retention.',
    },
    {
        id: 'juicy_animations',
        name: 'Juicy Animations',
        pillar: 'Design',
        icon: '💥',
        cost: 1500,
        capacityCost: 1,
        devTime: 1.0,
        quality: 1.0, innovation: 1.2, retention: 0.5, marketingPower: 1.0,
        risk: 0.05,
        tags: ['polish'],
        unlockCondition: { type: 'trend', trendId: 'immersive' },
        description: 'Bouncy, fast, and alive. High innovation and hype.',
    },
    {
        id: 'design_system',
        name: 'Design System',
        pillar: 'Design',
        icon: '💅',
        cost: 2500,
        capacityCost: 1,
        devTime: 1.5,
        quality: 2.0, innovation: 0.5, retention: 1.5, marketingPower: 0,
        risk: -0.2,
        tags: ['system'],
        unlockCondition: { type: 'mastery', releases: 4 },
        description: 'Comprehensive design framework. Reduces risk and boosts quality.',
    },

    // ── DEVELOPMENT ──────────────────────────────────────────────────────────
    {
        id: 'basic_stack',
        name: 'Basic Stack',
        pillar: 'Development',
        icon: '📦',
        cost: 500,
        capacityCost: 1,
        devTime: 0.5,
        quality: 0.6, innovation: 0, retention: 0, marketingPower: 0,
        risk: -0.05,
        tags: ['tech'],
        unlockCondition: { type: 'free' },
        description: 'Reliable foundation. Standard and safe.',
    },
    {
        id: 'bug_squash',
        name: 'Bug Squash Week',
        pillar: 'Development',
        icon: '🐞',
        cost: 800,
        capacityCost: 1,
        devTime: 0.8,
        quality: 0.2, innovation: 0, retention: 0.8, marketingPower: 0,
        risk: -0.3,
        tags: ['qa'],
        unlockCondition: { type: 'free' },
        description: 'Focus on stability. Drastically reduces failure risk.',
    },
    {
        id: 'modular_code',
        name: 'Modular Code',
        pillar: 'Development',
        icon: '🧩',
        cost: 1200,
        capacityCost: 1,
        devTime: 1.0,
        quality: 1.2, innovation: 0.5, retention: 0.5, marketingPower: 0,
        risk: -0.1,
        tags: ['tech'],
        unlockCondition: { type: 'free' },
        description: 'Clean and organized. Good quality and future-proofing.',
    },
    {
        id: 'performance_pass',
        name: 'Performance Pass',
        pillar: 'Development',
        icon: '⚡',
        cost: 900,
        capacityCost: 1,
        devTime: 0.6,
        quality: 0.5, innovation: 0.8, retention: 1.0, marketingPower: 0,
        risk: 0,
        tags: ['tech'],
        unlockCondition: { type: 'free' },
        description: 'Fast and responsive. Improves retention and innovation.',
    },
    {
        id: 'refactor_later',
        name: 'Refactor Later',
        pillar: 'Development',
        icon: '🏚️',
        cost: 100,
        capacityCost: 1,
        devTime: 0.1,
        quality: 0, innovation: 1.0, retention: -0.5, marketingPower: 0,
        risk: 0.2,
        tags: ['speed'],
        unlockCondition: { type: 'free' },
        description: 'Move fast, break things. Fast innovation but high risk.',
    },
    {
        id: 'auto_tests',
        name: 'Auto Tests',
        pillar: 'Development',
        icon: '🧪',
        cost: 2000,
        capacityCost: 1,
        devTime: 1.5,
        quality: 1.0, innovation: 0, retention: 1.5, marketingPower: 0,
        risk: -0.4,
        tags: ['qa'],
        unlockCondition: { type: 'mastery', releases: 4 },
        description: 'Automated reliability. The ultimate safety net.',
    },
    {
        id: 'scales_well',
        name: 'Scales Well',
        pillar: 'Development',
        icon: '⚖️',
        cost: 3000,
        capacityCost: 1,
        devTime: 2.0,
        quality: 1.5, innovation: 0.5, retention: 2.0, marketingPower: 0,
        risk: -0.1,
        tags: ['tech'],
        unlockCondition: { type: 'revenue', amount: 50000 },
        description: 'Architected for growth. Massive retention boost.',
    },

    // ── MARKETING ────────────────────────────────────────────────────────────
    {
        id: 'soft_launch',
        name: 'Soft Launch',
        pillar: 'Marketing',
        icon: '🎈',
        cost: 300,
        capacityCost: 1,
        devTime: 0.1,
        quality: 0, innovation: 0, retention: 0.3, marketingPower: 0.4,
        risk: -0.1,
        tags: ['launch'],
        unlockCondition: { type: 'free' },
        description: 'Quiet release. Test the waters and lower risk.',
    },
    {
        id: 'devlog',
        name: 'Devlogs',
        pillar: 'Marketing',
        icon: '📝',
        cost: 600,
        capacityCost: 1,
        devTime: 0.4,
        quality: 0, innovation: 0, retention: 0.6, marketingPower: 1.0,
        risk: 0,
        tags: ['content'],
        unlockCondition: { type: 'free' },
        description: 'Build in public. Steady hype and retention.',
    },
    {
        id: 'hype_trailer',
        name: 'Hype Trailer',
        pillar: 'Marketing',
        icon: '🎬',
        cost: 1500,
        capacityCost: 1,
        devTime: 0.8,
        quality: 0.5, innovation: 0.5, retention: 0, marketingPower: 2.5,
        risk: 0.1,
        tags: ['video'],
        unlockCondition: { type: 'free' },
        description: 'High energy video. Massive burst of marketing power.',
    },
    {
        id: 'influencer_dm',
        name: 'Influencer DMs',
        pillar: 'Marketing',
        icon: '✉️',
        cost: 800,
        capacityCost: 1,
        devTime: 0.3,
        quality: 0, innovation: 0, retention: 0, marketingPower: 1.8,
        risk: 0.05,
        tags: ['hype'],
        unlockCondition: { type: 'free' },
        description: 'Direct outreach. Fast hype with some risk.',
    },
    {
        id: 'community_discord',
        name: 'Community Discord',
        pillar: 'Marketing',
        icon: '💬',
        cost: 1200,
        capacityCost: 1,
        devTime: 0.5,
        quality: 0, innovation: 0.2, retention: 2.5, marketingPower: 0.5,
        risk: 0,
        tags: ['content'],
        unlockCondition: { type: 'free' },
        description: 'Build a home for users. Monster retention boost.',
    },
    {
        id: 'press_coverage',
        name: 'Press Coverage',
        pillar: 'Marketing',
        icon: '📰',
        cost: 3500,
        capacityCost: 1,
        devTime: 0.5,
        quality: 1.0, innovation: 0, retention: 0, marketingPower: 4.0,
        risk: 0.2,
        tags: ['launch'],
        unlockCondition: { type: 'fanbase', amount: 15000 },
        description: 'Mainstream attention. Extreme marketing power.',
    },
    {
        id: 'paid_ads',
        name: 'Paid Ads',
        pillar: 'Marketing',
        icon: '💰',
        cost: 6000,
        capacityCost: 1,
        devTime: 0,
        quality: 0, innovation: 0, retention: 0, marketingPower: 5.0,
        risk: 0.1,
        tags: ['hype'],
        unlockCondition: { type: 'revenue', amount: 200000 },
        description: 'Buying the market. Max marketing power.',
    },

    // ── EXCLUSIVE COMPONENTS (Software Type Locked) ──────────────────────────
    {
        id: 'game_feel_magic',
        name: 'Game Feel Magic',
        pillar: 'Design',
        icon: '🕹️',
        cost: 2000,
        capacityCost: 1,
        devTime: 1.2,
        quality: 1.0, innovation: 2.5, retention: 0.5, marketingPower: 0.5,
        risk: 0.4,
        exclusiveTo: 'indie_hit',
        unlockCondition: { type: 'free' },
        description: 'Secret sauce for games. Massive innovation, but extreme risk.',
    },
    {
        id: 'growth_loops',
        name: 'Growth Loops',
        pillar: 'Marketing',
        icon: '🔄',
        cost: 2500,
        capacityCost: 1,
        devTime: 0.8,
        quality: 0.5, innovation: 0.5, retention: 0, marketingPower: 3.5,
        risk: 0.1,
        exclusiveTo: 'everyday_app',
        unlockCondition: { type: 'free' },
        description: 'Users bring in users. Massive fan gain, but faster decay.',
    },
    {
        id: 'enterprise_contracts',
        name: 'Enterprise Deals',
        pillar: 'Marketing',
        icon: '🤝',
        cost: 5000,
        capacityCost: 2,
        devTime: 1.5,
        quality: 0.5, innovation: -0.5, retention: 1.0, marketingPower: 1.0,
        risk: -0.1,
        revenueMultiplier: 3.5,
        exclusiveTo: 'hustle_saas',
        unlockCondition: { type: 'free' },
        description: 'B2B focus. Massive revenue multiplier, but no virality.',
    },
    {
        id: 'pro_workflow_mode',
        name: 'Pro Workflow',
        pillar: 'Design',
        icon: '🎹',
        cost: 3000,
        capacityCost: 1,
        devTime: 1.5,
        quality: 1.0, innovation: 0, retention: 4.5, marketingPower: -1.0,
        risk: 0.05,
        exclusiveTo: 'power_tool',
        unlockCondition: { type: 'free' },
        description: 'Built for experts. Extreme retention, but niche appeal.',
    },
    {
        id: 'rock_solid_api',
        name: 'Rock-Solid API',
        pillar: 'Development',
        icon: '🔌',
        cost: 4000,
        capacityCost: 1,
        devTime: 2.5,
        quality: 2.0, innovation: 0, retention: 5.0, marketingPower: -0.5,
        risk: -0.2,
        exclusiveTo: 'dev_playground',
        unlockCondition: { type: 'free' },
        description: 'Unbreakable foundation. Almost no decay, very slow growth.',
    },

    // ── ACHIEVEMENT-BASED COMPONENTS ─────────────────────────────────────────
    {
        id: 'indie_darling_stat',
        name: 'Indie Darling',
        pillar: 'Ideation',
        icon: '💖',
        cost: 1000,
        capacityCost: 1,
        devTime: 0.5,
        quality: 1.5, innovation: 0, retention: 1.0, marketingPower: 0,
        risk: -0.1,
        unlockCondition: { type: 'achievement', id: 'indie_darling' },
        description: 'Unlocked by a high-rated Indie Hit. Boosts quality and reliability.',
    },
    {
        id: 'fan_favorite_stat',
        name: 'Fan Favorite',
        pillar: 'Marketing',
        icon: '⭐',
        cost: 2000,
        capacityCost: 1,
        devTime: 0.2,
        quality: 1.0, innovation: 0, retention: 2.0, marketingPower: 1.5,
        risk: 0,
        unlockCondition: { type: 'achievement', id: 'fan_favorite' },
        description: 'Unlocked at 25k fans. Massive retention and hype.',
    },
    {
        id: 'shipped_anyway_stat',
        name: 'Shipped Anyway',
        pillar: 'Development',
        icon: '🚀',
        cost: 500,
        capacityCost: 1,
        devTime: 0.1,
        quality: 0.5, innovation: 1.5, retention: 0, marketingPower: 0.5,
        risk: 0.1,
        unlockCondition: { type: 'achievement', id: 'shipped_anyway' },
        description: 'Unlocked by a mediocre launch. High innovation spike.',
    },
    {
        id: 'giant_killer_stat',
        name: 'Giant Killer',
        pillar: 'Ideation',
        icon: '🗡️',
        cost: 3000,
        capacityCost: 1,
        devTime: 1.0,
        quality: 2.0, innovation: 2.0, retention: 1.0, marketingPower: 0,
        risk: 0.2,
        unlockCondition: { type: 'achievement', id: 'giant_killer' },
        description: 'Unlocked by beating a GIANT. Massive power spike.',
    },
    {
        id: 'serial_builder_stat',
        name: 'Serial Builder',
        pillar: 'Ideation',
        icon: '🏗️',
        cost: 4000,
        capacityCost: 1,
        devTime: 1.5,
        quality: 1.5, innovation: 1.5, retention: 1.5, marketingPower: 1.5,
        risk: -0.1,
        unlockCondition: { type: 'achievement', id: 'serial_builder' },
        description: 'Unlocked after 10 launches. Strong across all stats.',
    },
];

// ── SYNERGIES (Expanded to 18) ────────────────────────────────────────────────
export const SYNERGIES = [
    {
        id: 'indie_darling_synergy',
        label: '💖 Indie Darling',
        components: ['clear_idea', 'devlog'],
        bonus: { criticsScore: 1.5, fanGain: 1.2 },
        description: 'Critics love a clear vision shared publicly.',
    },
    {
        id: 'hype_machine',
        label: '🚀 Hype Machine',
        components: ['brand_vibes', 'influencer_dm'],
        bonus: { viralChance: 0.15, marketingPower: 1.5 },
        description: 'Visual identity meets direct promotion.',
    },
    {
        id: 'rock_solid',
        label: '🛡️ Rock Solid',
        components: ['bug_squash', 'modular_code'],
        bonus: { risk: -0.3, quality: 0.8 },
        description: 'Stable code and organized architecture.',
    },
    {
        id: 'cult_app',
        label: '🕯️ Cult App',
        components: ['scratch_itch', 'community_discord'],
        bonus: { retention: 3.0, fanGain: 1.5 },
        description: 'Personal solutions build loyal communities.',
    },
    {
        id: 'corporate_lock_in',
        label: '🏢 Corporate Lock-In',
        components: ['enterprise_contracts', 'scales_well'],
        bonus: { revenueMultiplier: 1.5, lifespan: 24 },
        description: 'B2B deals on a stable backend last forever.',
    },
    {
        id: 'focus_point',
        label: '🔍 Focus Point',
        components: ['small_focused', 'performance_pass'],
        bonus: { quality: 1.2, retention: 1.0 },
        description: 'Speed and focus result in extreme quality.',
    },
    {
        id: 'viral_loop',
        label: '🔄 Viral Loop',
        components: ['growth_loops', 'hype_trailer'],
        bonus: { viralChance: 0.1, fanGain: 2.5 },
        description: 'A hype trailer fueled by growth loops.',
    },
    {
        id: 'market_polish',
        label: '💎 Market Polish',
        components: ['feels_polished', 'press_coverage'],
        bonus: { quality: 1.5, marketingPower: 2.0 },
        description: 'Mainstream press meets premium design.',
    },
    {
        id: 'os_utility',
        label: '🖥️ OS Utility',
        components: ['dark_mode', 'modular_code'],
        bonus: { quality: 1.0, marketShareGain: 1.5 },
        description: 'Clean visuals and clean architecture.',
    },
    {
        id: 'pro_suite',
        label: '🎹 Pro Suite',
        components: ['pro_workflow_mode', 'clean_look'],
        bonus: { retention: 2.0, quality: 1.0 },
        description: 'Expert tools that look great.',
    },
    {
        id: 'dev_standard',
        label: '🧪 Dev Standard',
        components: ['rock_solid_api', 'auto_tests'],
        bonus: { lifespan: 36, risk: -0.2 },
        description: 'APIs backed by tests become industry standards.',
    },
    {
        id: 'shadow_launch',
        label: '🎈 Shadow Launch',
        components: ['soft_launch', 'basic_stack'],
        bonus: { risk: -0.2, marketingPower: 0.5 },
        description: 'Quiet release on a stable base minimizes failure.',
    },
    {
        id: 'trend_master',
        label: '🌊 Trend Master',
        components: ['trend_surfing', 'juicy_animations', 'clean_look'], // 3 components synergy
        bonus: { innovation: 2.0, marketingPower: 3.0 },
        description: 'The ultimate trend-riding combination.',
    },
    {
        id: 'scale_strategy',
        label: '⚖️ Scale Strategy',
        components: ['audience_first', 'scales_well'],
        bonus: { retention: 1.5, revenueMultiplier: 1.2 },
        description: 'Audience data meeting scalable infrastructure.',
    },
    {
        id: 'brand_loyalty',
        label: '🎨 Brand Loyalty',
        components: ['brand_vibes', 'community_discord'],
        bonus: { fanGain: 2.0, retention: 1.5 },
        description: 'Strong visuals and community engagement.',
    },
    {
        id: 'indie_darling_v2',
        label: '💖 Indie Darling+',
        components: ['indie_darling_stat', 'devlog'],
        bonus: { quality: 1.0, fanGain: 2.0 },
        description: 'Double down on the indie path.',
    },
    {
        id: 'giant_slayer',
        label: '🗡️ Giant Slayer',
        components: ['giant_killer_stat', 'press_coverage'],
        bonus: { marketShareGain: 5.0, marketingPower: 3.0 },
        description: 'Aggressive press for the industry disruptor.',
    },
    {
        id: 'mvp_speed',
        label: '🏚️ MVP Speed',
        components: ['refactor_later', 'copy_works'],
        bonus: { innovation: 1.5, devTimeMultiplier: 0.5 },
        description: 'Fastest possible path to market.',
    },
];

export function getComponentById(id) {
    return COMPONENTS.find(c => c.id === id);
}

export function getActiveComponents(selectedIds) {
    return selectedIds.map(getComponentById).filter(Boolean);
}

export function detectSynergies(selectedIds) {
    return SYNERGIES.filter(s => s.components.every(id => selectedIds.includes(id)));
}
